# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WCV0eSFCHFz3RVTezRd3z-PkQOAS3MOA
"""

import sys
print(sys.version)

import tensorflow as tf
print(tf.__version__)

import numpy as np
from numpy import loadtxt

data = loadtxt('/content/diabetesclean.csv', delimiter=',')

data.shape

x = data[:,0:8]
y = data[:,8]

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

from keras.models import Sequential
from keras.layers import Dense

model = Sequential()

model.add(Dense(8,input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(x_train,y_train,epochs=300,batch_size=40)

_,acc = model.evaluate(x_test,y_test)
print("Accuracy score for test data",acc)

print(x_test[0],y_test[0])